### ISSUE TITLE
We have too many notebooks

### ISSUE THREAD

**Issue by eni0tna** [joaocaldass/inriamericwaves#5]
How should we do? Grouping notebooks in carpetas or writing a README file, or both?

**Comment by joaocaldass** [comment]
About organizing the files in folders, apparently Python can only import modules in the same directory (something like import "../nswe/muscl2.py" does not work).

Google told me to tell Python the folders to search in:

import sys
sys.path.append('../nswe')
import muscl2

I don't know if it's the best solution, maybe José knows to handle it

**Comment by jgalazm** [comment]
Other thing we could try is to add the "Simulations" folder to the
PYTHONPATH environment variable, in the bashrc file.

It should be something like

export PYTHONPATH = $PYTHONPATH:/the/Simulations/folder

Then try the import.
