### ISSUE TITLE
Oscillations near shocks in NSWE solver

### ISSUE THREAD

**Issue by jgalazm** [joaocaldass/inriamericwaves#8]
I'm looking at this file 

[Simulations/DDM_NSWE_Serre/DDM_NSWE_Serre.ipynb#Only-NSWE](https://github.com/joaocaldass/inriamericwaves/blob/master/Simulations/DDM_NSWE_Serre/DDM_NSWE_Serre_NonHorizontal.ipynb)

If I understand, the oscillations  are visible in cell number 13:

![image](https://cloud.githubusercontent.com/assets/3409401/19628399/47da9566-9933-11e6-8ff9-5e86d24e6a82.png)

Is this what you guys mean? @eni0tna @joaocaldass

**Comment by jgalazm** [comment]
The 4th order NSWE scheme does not include flux limiters so it won't handle properly large discontinuities (shocks), hence it should only be applied to waves of small amplitude (that is a1/a0, according to variables in the notebook).

If I change the amplitude `a1` from 0.1 to 0.01, which is in a smaller scale than the reference depth a0=0.3, this ensures me no shock formation and the scheme behaves well. 

![image](https://cloud.githubusercontent.com/assets/3409401/19628481/f0aa72be-9934-11e6-888c-4e92436030e4.png)

This is because the ratio a1/a0 has to be very small to not to obtain shock-waves.

What do you think @joaocaldass? Does it solve the problem?

**Comment by joaocaldass** [comment]
Thanks José :D

I will modify the tests to use this configuration. Now it will be easier to
study the results

**Comment by jgalazm** [comment]
Great, Im closing this issue then.
